### PR TITLE
Fixes PBXObject equality

### LINKED ISSUE #223: PBXObject Equatable is broken
#218 broke Equatable even more. Every `PBXObject` subclass now incorrectly returns true for every comparison, which also means many will always incorrectly pass.
It looks like the previous implementation was also not working as subclasses didn't check their parents and superclasses didn't call down to subclasses.
The fix for this should be the addition of Sourcery templates what work well with classes

### PR DESCRIPTION
**Pull request by yonaskolb**
Resolves #223

This makes PBXObject conform to `Equatable` which then calls out to an instance method that all subclasses override. When we move to Sourcery we can remove all of this

---
This change is [Reviewable](https://reviewable.io/reviews/xcodeswift/xcproj/224)

### CODE REVIEW

**Comment by yonaskolb** [comment]
@pepibumur do you know why the tests are failing?

**Comment by pepibumur** [comment]
@yonaskolb, apparently there are some tests that are failing:
image

File: Tests/xcprojTests/PBXRezBuildPhaseSpec.swift [hunk 1]
```diff
@@ -22,7 +22,7 @@ final class PBXRezBuildPhaseSpec: XCTestCase {
     }
 
     func test_equals_returnsTheCorrectValue() {
-        let another = PBXResourcesBuildPhase(files: ["123"],
+        let another = PBXRezBuildPhase(files: ["123"],
```
Comment (yonaskolb) [inline Tests/xcprojTests/PBXRezBuildPhaseSpec.swift]: This is an example of something that was incorrectly passing tests

Comment (pepibumur) [reply Tests/xcprojTests/PBXRezBuildPhaseSpec.swift]: :/ we need Sourcery
